version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: github.com/grpc-ecosystem/grpc-gateway/v2
    versions:
    - 2.1.0
    - 2.2.0
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
