name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Fetch Config
        id: configfetch
        uses: anant-sharma/chip-config-fetch@v2.8.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and Push Image
        if: success()
        uses: docker/build-push-action@v2
        with:
          username: ${{ steps.configfetch.outputs.DOCKER_USER }}
          password: ${{ steps.configfetch.outputs.DOCKER_PASS }}
          repository: ${{steps.configfetch.outputs.DOCKER_USER}}/${{steps.configfetch.outputs.DOCKER_IMAGE_NAME}}
          tags: ${{steps.configfetch.outputs.TAG}}

      - name: Deploy to Chip Cluster
        if: success()
        uses: anant-sharma/chip-config-fetch@v2.8.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          deploy: "1"

      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          author_name: ${{ env.GITHUB_ACTOR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ steps.configfetch.outputs.SLACK_WEBHOOK }}
