name: Build
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Fetch Config
        id: configfetch
        uses: anant-sharma/chip-config-fetch@v2.9.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ steps.configfetch.outputs.DOCKER_USER }}
          password: ${{ steps.configfetch.outputs.DOCKER_PASS }}

      - name: Build and Push Image
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{steps.configfetch.outputs.DOCKER_USER}}/${{steps.configfetch.outputs.DOCKER_IMAGE_NAME}}:${{steps.configfetch.outputs.TAG}}
            ${{steps.configfetch.outputs.DOCKER_USER}}/${{steps.configfetch.outputs.DOCKER_IMAGE_NAME}}:${{github.sha}}

      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          author_name: ${{ env.GITHUB_ACTOR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ steps.configfetch.outputs.SLACK_WEBHOOK }}
